attributes:
  GENERIC_MAX_HEALTH:
    display: "MAX_HEALTH"
    maxPercent: 15
  GENERIC_FOLLOW_RANGE:
    display: "FOLLOW_RANGE"
    maxPercent: 15
  GENERIC_KNOCKBACK_RESISTANCE:
    display: "KNOCKBACK_RESISTANCE"
    maxPercent: 15
  GENERIC_MOVEMENT_SPEED:
    display: "MOVEMENT_SPEED"
    maxPercent: 15
  GENERIC_ATTACK_DAMAGE:
    display: "ATTACK_DAMAGE"
    maxPercent: 15
  GENERIC_ATTACK_SPEED:
    display: "ATTACK_SPEED"
    maxPercent: 15
  GENERIC_ARMOR:
    display: "ARMOR"
    maxPercent: 15
  GENERIC_ARMOR_TOUGHNESS:
    display: "ARMOR"
    maxPercent: 15
  GENERIC_LUCK:
    display: "LUCK"
    maxPercent: 15

drops:
  n:
    enchants: 0
    attributes: 1
    list:
      - ZOMBIE
      - SPIDER
  r:
    enchants: 0
    attributes: 2
    list:
      - SKELETON
  sr:
    enchants: 1
    attributes: 2
    list:
      - CREEPER
      - ENDERMAN
  ssr:
    enchants: 2
    attributes: 2

random:
  start: 0.2
  maxDrops: 3
  mob_spawn:
    named: 0.01
    equipped: 0.08

disabled_world:
  - disabled_world

named_boss_settings:
  money: 1000.0
  health:
    min: 30
    max: 100
  follow_range:
    min: 50.0
    max: 70.0
  knockback_resistance:
    min: 0.05
    max: 1
  movement_speed:
    min: 0.1
    max: 0.5
  armor:
    min: 1
    max: 30
  atk_dmg:
    min: 3
    max: 10



named_boss_list:
  - A
  - B
  - C
  - D
  - E
  - F
  - G
  - H
  - I
  - J
  - K
  - L
  - M
  - N
  - O
  - P