name: ELRPGItem
version: ${project.version}
main: com.ericlam.mc.elrpgitem.ELRpgItem
api-version: "1.15"
depend: [KotLib, XuanCatAPI, Vault]
softdepend: [MMOItems]
commands:
  elrpg:
    description: elrpg command
    permission: elrpg.admin